name: Build Image
on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - '**.md'
    schedule:
        - cron: '30 4 * * 0' # At 04:30 on every Sunday.
    workflow_dispatch:

env:
    IMAGE_NAME: '${{ github.event.repository.name }}'
    IMAGE_DESC: 'My Customized uCore Image'
    IMAGE_VENDOR: ${{ github.repository_owner }}
    IMAGE_REGISTRY: 'ghcr.io/${{ github.repository_owner }}'
    DEFAULT_TAG: 'latest'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
    cancel-in-progress: true

jobs:
    build_push:
        name: Build and Push Image
        runs-on: ubuntu-24.04

        permissions:
            contents: read
            packages: write
            id-token: write

        outputs:
            build_date: ${{ steps.date.outputs.build_date }}
            version: ${{ steps.generate_tags.outputs.version }}

        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            # This is optional, but if you see that your builds are way too big for the runners, you can enable this by uncommenting the following lines:
            # - name: Maximize Build Space
            #   uses: ublue-os/remove-unwanted-software@v8
            #   with:
            #       remove-codeql: true

            - name: Get Current Date
              id: date
              run: |
                  echo "build_date=$(date -u +%Y\-%m\-%d\T%H\:%M\:%S\Z)" >> $GITHUB_OUTPUT
                  echo "tag_date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

            - name: Fetch Upstream Versions
              id: fetch
              run: |
                  skopeo inspect docker://ghcr.io/ublue-os/ucore:stable > inspect.json

                  image=$(jq -r '.["Labels"]["org.opencontainers.image.version"]' inspect.json)
                  if [ -z "$image" ] || [ "null" = "$image" ]; then
                      echo "Inspected image version must not be empty or null"
                      exit 1
                  fi

                  fedora=$(echo "$image" | cut -f1 -d.)
                  if [ -z "$fedora" ] || [ "null" = "$fedora" ]; then
                      echo "Fedora version must not be empty or null"
                      exit 1
                  fi

                  echo "fedora_version=$fedora" >> $GITHUB_OUTPUT

            # Generate tags and suffix it by .1, .2, etc if the same
            - name: Generate Tags
              id: generate_tags
              shell: bash
              run: |
                  version=${{ steps.fetch.outputs.fedora_version }}.${{ steps.date.outputs.tag_date }}

                  tags=$(gh api repos/${{ github.repository }}/releases --jq '[.[].tag_name | select(startswith("'"${version}"'"))] | sort_by(.)')

                  if [ -z "$tags" ] || [ "$tags" == "[]" ]; then
                      echo "version=${version}" >> $GITHUB_OUTPUT
                  else
                      latest=$(echo "$tags" | jq -r '.[-1]')
                      
                      if [[ $latest == $version ]]; then
                          echo "version=${version}.1" >> $GITHUB_OUTPUT
                      else
                          num=$(echo $latest | awk -F. '{print $3}')
                          next=$((num + 1))
                          echo "version=${version}.${next}" >> $GITHUB_OUTPUT
                      fi
                  fi
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Image Metadata
              uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
              id: metadata
              with:
                  # This generates all the tags for your image, you can add custom tags here too!
                  tags: |
                      type=raw,value=latest
                      type=raw,value=${{ steps.generate_tags.outputs.version }}
                      type=sha,enable=${{ github.event_name == 'pull_request' }}
                      type=ref,event=pr
                  labels: |
                      org.opencontainers.image.created=${{ steps.date.outputs.build_date }}
                      org.opencontainers.image.description=${{ env.IMAGE_DESC }}
                      org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/refs/heads/main/README.md
                      org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/blob/main/Containerfile
                      org.opencontainers.image.title=${{ env.IMAGE_NAME }}
                      org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
                      org.opencontainers.image.vendor=${{ github.repository_owner }}
                      org.opencontainers.image.version=${{ steps.generate_tags.outputs.version }}
                      containers.bootc=1
                  sep-tags: ' '
                  sep-annotations: ' '

            - name: Build Image
              id: build_image
              uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
              with:
                  containerfiles: |
                      ./Containerfile
                  image: ${{ env.IMAGE_NAME }}
                  tags: ${{ steps.metadata.outputs.tags }}
                  labels: ${{ steps.metadata.outputs.labels }}
                  oci: false

            # These `if` statements are so that pull requests for your custom images do not make it publish any packages under your name without you knowing
            # They also check if the runner is on the default branch so that things like the merge queue (if you enable it), are going to work
            - name: Login to GitHub Container Registry
              uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
              if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
            # https://github.com/macbre/push-to-ghcr/issues/12
            - name: Lowercase Registry
              id: registry_case
              uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
              with:
                  string: ${{ env.IMAGE_REGISTRY }}

            - name: Lowercase Image
              id: image_case
              uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
              with:
                  string: ${{ env.IMAGE_NAME }}

            - name: Push to GHCR
              uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
              if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              id: push
              env:
                  REGISTRY_USER: ${{ github.actor }}
                  REGISTRY_PASSWORD: ${{ github.token }}
              with:
                  registry: ${{ steps.registry_case.outputs.lowercase }}
                  image: ${{ steps.image_case.outputs.lowercase }}
                  tags: ${{ steps.metadata.outputs.tags }}
                  username: ${{ env.REGISTRY_USER }}
                  password: ${{ env.REGISTRY_PASSWORD }}

            # This section is optional and only needs to be enabled if you plan on distributing
            # your project for others to consume. You will need to create a public and private key
            # using Cosign and save the private key as a repository secret in Github for this workflow
            # to consume. For more details, review the image signing section of the README.
            - name: Install Cosign
              uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2
              if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

            - name: Sign Container Image
              if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              run: |
                  IMAGE_FULL="${{ steps.registry_case.outputs.lowercase }}/${{ steps.image_case.outputs.lowercase }}"
                  for tag in ${{ steps.metadata.outputs.tags }}; do
                    cosign sign -y --key env://COSIGN_PRIVATE_KEY $IMAGE_FULL:$tag
                  done
              env:
                  TAGS: ${{ steps.push.outputs.digest }}
                  COSIGN_EXPERIMENTAL: false
                  COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

    generate_release:
        name: Generate Release
        needs: [build_push]
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: ./.github/workflows/generate-release.yml
        secrets: inherit
        with:
            build_date: ${{ needs.build_push.outputs.build_date }}
            version: ${{ needs.build_push.outputs.version }}

        permissions:
            contents: write
